### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by jmcquarr** [jmcquarr/protospace-39766#1]
https://protospace-39766.onrender.com/

**Comment by yusuketono** [comment]
@jmcquarr さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### プロトタイプ一覧表示機能
- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプ名をクリックしても遷移しないので修正をお願いします。
(画像の方は問題ございません！)

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by jmcquarr** [comment]
プロトタイプ名もクリックするとプロトタイプの詳細ページへ遷移するように修正しました

**Comment by OhyaYouki** [comment]
レビュー依頼ありがとうございます！

全ての挙動が確認できましたのでLGTMとさせていただきます！
実装お疲れ様でした！
